//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Zero_2.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ValidationSoap", Namespace="http://tempuri.org/")]
    public partial class Validation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ApproveAttestationRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveAttestationUnPlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveAttestationReOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveAttestationOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveDataDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GovernmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fill_CommissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Commission_AppointedOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatementReverseOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthentificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback Date_PlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback Date_RepeatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback DateRepeatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback Date_UnPlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback DateSurpriseOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Date_SurpriseOperationCompleted;
        
        private System.Threading.SendOrPostCallback Validation_DutyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CommisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback WantRiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback Date_ValidationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback DateRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback whOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GovernmentManOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Validation() {
            this.Url = global::Zero_2.Properties.Settings.Default.Zero_2_localhost_Validation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ApproveAttestationRequestCompletedEventHandler ApproveAttestationRequestCompleted;
        
        /// <remarks/>
        public event ApproveAttestationUnPlanCompletedEventHandler ApproveAttestationUnPlanCompleted;
        
        /// <remarks/>
        public event ApproveAttestationReCompletedEventHandler ApproveAttestationReCompleted;
        
        /// <remarks/>
        public event ApproveAttestationCompletedEventHandler ApproveAttestationCompleted;
        
        /// <remarks/>
        public event ApproveDataDeleteCompletedEventHandler ApproveDataDeleteCompleted;
        
        /// <remarks/>
        public event ApproveDataCompletedEventHandler ApproveDataCompleted;
        
        /// <remarks/>
        public event GovernmentCompletedEventHandler GovernmentCompleted;
        
        /// <remarks/>
        public event Fill_CommissionCompletedEventHandler Fill_CommissionCompleted;
        
        /// <remarks/>
        public event Commission_AppointedCompletedEventHandler Commission_AppointedCompleted;
        
        /// <remarks/>
        public event StatementReverseCompletedEventHandler StatementReverseCompleted;
        
        /// <remarks/>
        public event StatementCompletedEventHandler StatementCompleted;
        
        /// <remarks/>
        public event ProFileCompletedEventHandler ProFileCompleted;
        
        /// <remarks/>
        public event AuthentificationCompletedEventHandler AuthentificationCompleted;
        
        /// <remarks/>
        public event Date_PlanCompletedEventHandler Date_PlanCompleted;
        
        /// <remarks/>
        public event Date_RepeatedCompletedEventHandler Date_RepeatedCompleted;
        
        /// <remarks/>
        public event DateRepeatedCompletedEventHandler DateRepeatedCompleted;
        
        /// <remarks/>
        public event Date_UnPlanCompletedEventHandler Date_UnPlanCompleted;
        
        /// <remarks/>
        public event DateSurpriseCompletedEventHandler DateSurpriseCompleted;
        
        /// <remarks/>
        public event ExistsCompletedEventHandler ExistsCompleted;
        
        /// <remarks/>
        public event Date_SurpriseCompletedEventHandler Date_SurpriseCompleted;
        
        /// <remarks/>
        public event Validation_DutyCompletedEventHandler Validation_DutyCompleted;
        
        /// <remarks/>
        public event CommisionCompletedEventHandler CommisionCompleted;
        
        /// <remarks/>
        public event InsertCompletedEventHandler InsertCompleted;
        
        /// <remarks/>
        public event WantRiceCompletedEventHandler WantRiceCompleted;
        
        /// <remarks/>
        public event Date_ValidationCompletedEventHandler Date_ValidationCompleted;
        
        /// <remarks/>
        public event RequestCompletedEventHandler RequestCompleted;
        
        /// <remarks/>
        public event DateRequestCompletedEventHandler DateRequestCompleted;
        
        /// <remarks/>
        public event whCompletedEventHandler whCompleted;
        
        /// <remarks/>
        public event EmployeesCompletedEventHandler EmployeesCompleted;
        
        /// <remarks/>
        public event GovernmentManCompletedEventHandler GovernmentManCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveAttestationRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApproveAttestationRequest(string date1) {
            this.Invoke("ApproveAttestationRequest", new object[] {
                        date1});
        }
        
        /// <remarks/>
        public void ApproveAttestationRequestAsync(string date1) {
            this.ApproveAttestationRequestAsync(date1, null);
        }
        
        /// <remarks/>
        public void ApproveAttestationRequestAsync(string date1, object userState) {
            if ((this.ApproveAttestationRequestOperationCompleted == null)) {
                this.ApproveAttestationRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveAttestationRequestOperationCompleted);
            }
            this.InvokeAsync("ApproveAttestationRequest", new object[] {
                        date1}, this.ApproveAttestationRequestOperationCompleted, userState);
        }
        
        private void OnApproveAttestationRequestOperationCompleted(object arg) {
            if ((this.ApproveAttestationRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveAttestationRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveAttestationUnPlan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApproveAttestationUnPlan(string date1, string date2) {
            this.Invoke("ApproveAttestationUnPlan", new object[] {
                        date1,
                        date2});
        }
        
        /// <remarks/>
        public void ApproveAttestationUnPlanAsync(string date1, string date2) {
            this.ApproveAttestationUnPlanAsync(date1, date2, null);
        }
        
        /// <remarks/>
        public void ApproveAttestationUnPlanAsync(string date1, string date2, object userState) {
            if ((this.ApproveAttestationUnPlanOperationCompleted == null)) {
                this.ApproveAttestationUnPlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveAttestationUnPlanOperationCompleted);
            }
            this.InvokeAsync("ApproveAttestationUnPlan", new object[] {
                        date1,
                        date2}, this.ApproveAttestationUnPlanOperationCompleted, userState);
        }
        
        private void OnApproveAttestationUnPlanOperationCompleted(object arg) {
            if ((this.ApproveAttestationUnPlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveAttestationUnPlanCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveAttestationRe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApproveAttestationRe(string date1, string date2) {
            this.Invoke("ApproveAttestationRe", new object[] {
                        date1,
                        date2});
        }
        
        /// <remarks/>
        public void ApproveAttestationReAsync(string date1, string date2) {
            this.ApproveAttestationReAsync(date1, date2, null);
        }
        
        /// <remarks/>
        public void ApproveAttestationReAsync(string date1, string date2, object userState) {
            if ((this.ApproveAttestationReOperationCompleted == null)) {
                this.ApproveAttestationReOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveAttestationReOperationCompleted);
            }
            this.InvokeAsync("ApproveAttestationRe", new object[] {
                        date1,
                        date2}, this.ApproveAttestationReOperationCompleted, userState);
        }
        
        private void OnApproveAttestationReOperationCompleted(object arg) {
            if ((this.ApproveAttestationReCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveAttestationReCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveAttestation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApproveAttestation(string column) {
            this.Invoke("ApproveAttestation", new object[] {
                        column});
        }
        
        /// <remarks/>
        public void ApproveAttestationAsync(string column) {
            this.ApproveAttestationAsync(column, null);
        }
        
        /// <remarks/>
        public void ApproveAttestationAsync(string column, object userState) {
            if ((this.ApproveAttestationOperationCompleted == null)) {
                this.ApproveAttestationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveAttestationOperationCompleted);
            }
            this.InvokeAsync("ApproveAttestation", new object[] {
                        column}, this.ApproveAttestationOperationCompleted, userState);
        }
        
        private void OnApproveAttestationOperationCompleted(object arg) {
            if ((this.ApproveAttestationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveAttestationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveDataDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApproveDataDelete(string column) {
            this.Invoke("ApproveDataDelete", new object[] {
                        column});
        }
        
        /// <remarks/>
        public void ApproveDataDeleteAsync(string column) {
            this.ApproveDataDeleteAsync(column, null);
        }
        
        /// <remarks/>
        public void ApproveDataDeleteAsync(string column, object userState) {
            if ((this.ApproveDataDeleteOperationCompleted == null)) {
                this.ApproveDataDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveDataDeleteOperationCompleted);
            }
            this.InvokeAsync("ApproveDataDelete", new object[] {
                        column}, this.ApproveDataDeleteOperationCompleted, userState);
        }
        
        private void OnApproveDataDeleteOperationCompleted(object arg) {
            if ((this.ApproveDataDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveDataDeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApproveData(string id, string column) {
            this.Invoke("ApproveData", new object[] {
                        id,
                        column});
        }
        
        /// <remarks/>
        public void ApproveDataAsync(string id, string column) {
            this.ApproveDataAsync(id, column, null);
        }
        
        /// <remarks/>
        public void ApproveDataAsync(string id, string column, object userState) {
            if ((this.ApproveDataOperationCompleted == null)) {
                this.ApproveDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveDataOperationCompleted);
            }
            this.InvokeAsync("ApproveData", new object[] {
                        id,
                        column}, this.ApproveDataOperationCompleted, userState);
        }
        
        private void OnApproveDataOperationCompleted(object arg) {
            if ((this.ApproveDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Government", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Government() {
            object[] results = this.Invoke("Government", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GovernmentAsync() {
            this.GovernmentAsync(null);
        }
        
        /// <remarks/>
        public void GovernmentAsync(object userState) {
            if ((this.GovernmentOperationCompleted == null)) {
                this.GovernmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGovernmentOperationCompleted);
            }
            this.InvokeAsync("Government", new object[0], this.GovernmentOperationCompleted, userState);
        }
        
        private void OnGovernmentOperationCompleted(object arg) {
            if ((this.GovernmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GovernmentCompleted(this, new GovernmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fill_Commission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Fill_Commission(string fill) {
            object[] results = this.Invoke("Fill_Commission", new object[] {
                        fill});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Fill_CommissionAsync(string fill) {
            this.Fill_CommissionAsync(fill, null);
        }
        
        /// <remarks/>
        public void Fill_CommissionAsync(string fill, object userState) {
            if ((this.Fill_CommissionOperationCompleted == null)) {
                this.Fill_CommissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFill_CommissionOperationCompleted);
            }
            this.InvokeAsync("Fill_Commission", new object[] {
                        fill}, this.Fill_CommissionOperationCompleted, userState);
        }
        
        private void OnFill_CommissionOperationCompleted(object arg) {
            if ((this.Fill_CommissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fill_CommissionCompleted(this, new Fill_CommissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Commission_Appointed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Commission_Appointed(string p) {
            object[] results = this.Invoke("Commission_Appointed", new object[] {
                        p});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Commission_AppointedAsync(string p) {
            this.Commission_AppointedAsync(p, null);
        }
        
        /// <remarks/>
        public void Commission_AppointedAsync(string p, object userState) {
            if ((this.Commission_AppointedOperationCompleted == null)) {
                this.Commission_AppointedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommission_AppointedOperationCompleted);
            }
            this.InvokeAsync("Commission_Appointed", new object[] {
                        p}, this.Commission_AppointedOperationCompleted, userState);
        }
        
        private void OnCommission_AppointedOperationCompleted(object arg) {
            if ((this.Commission_AppointedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Commission_AppointedCompleted(this, new Commission_AppointedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StatementReverse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StatementReverse(string workbook) {
            this.Invoke("StatementReverse", new object[] {
                        workbook});
        }
        
        /// <remarks/>
        public void StatementReverseAsync(string workbook) {
            this.StatementReverseAsync(workbook, null);
        }
        
        /// <remarks/>
        public void StatementReverseAsync(string workbook, object userState) {
            if ((this.StatementReverseOperationCompleted == null)) {
                this.StatementReverseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatementReverseOperationCompleted);
            }
            this.InvokeAsync("StatementReverse", new object[] {
                        workbook}, this.StatementReverseOperationCompleted, userState);
        }
        
        private void OnStatementReverseOperationCompleted(object arg) {
            if ((this.StatementReverseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatementReverseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Statement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Statement(string workbook) {
            this.Invoke("Statement", new object[] {
                        workbook});
        }
        
        /// <remarks/>
        public void StatementAsync(string workbook) {
            this.StatementAsync(workbook, null);
        }
        
        /// <remarks/>
        public void StatementAsync(string workbook, object userState) {
            if ((this.StatementOperationCompleted == null)) {
                this.StatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatementOperationCompleted);
            }
            this.InvokeAsync("Statement", new object[] {
                        workbook}, this.StatementOperationCompleted, userState);
        }
        
        private void OnStatementOperationCompleted(object arg) {
            if ((this.StatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ProFile(string login, ref string[] array1, ref string[] array2, ref string[] array3) {
            object[] results = this.Invoke("ProFile", new object[] {
                        login,
                        array1,
                        array2,
                        array3});
            array1 = ((string[])(results[0]));
            array2 = ((string[])(results[1]));
            array3 = ((string[])(results[2]));
        }
        
        /// <remarks/>
        public void ProFileAsync(string login, string[] array1, string[] array2, string[] array3) {
            this.ProFileAsync(login, array1, array2, array3, null);
        }
        
        /// <remarks/>
        public void ProFileAsync(string login, string[] array1, string[] array2, string[] array3, object userState) {
            if ((this.ProFileOperationCompleted == null)) {
                this.ProFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProFileOperationCompleted);
            }
            this.InvokeAsync("ProFile", new object[] {
                        login,
                        array1,
                        array2,
                        array3}, this.ProFileOperationCompleted, userState);
        }
        
        private void OnProFileOperationCompleted(object arg) {
            if ((this.ProFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProFileCompleted(this, new ProFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Authentification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Authentification(string login, string password, ref int who) {
            object[] results = this.Invoke("Authentification", new object[] {
                        login,
                        password,
                        who});
            who = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthentificationAsync(string login, string password, int who) {
            this.AuthentificationAsync(login, password, who, null);
        }
        
        /// <remarks/>
        public void AuthentificationAsync(string login, string password, int who, object userState) {
            if ((this.AuthentificationOperationCompleted == null)) {
                this.AuthentificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthentificationOperationCompleted);
            }
            this.InvokeAsync("Authentification", new object[] {
                        login,
                        password,
                        who}, this.AuthentificationOperationCompleted, userState);
        }
        
        private void OnAuthentificationOperationCompleted(object arg) {
            if ((this.AuthentificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthentificationCompleted(this, new AuthentificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Date_Plan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Date_Plan(string val, string val1) {
            object[] results = this.Invoke("Date_Plan", new object[] {
                        val,
                        val1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Date_PlanAsync(string val, string val1) {
            this.Date_PlanAsync(val, val1, null);
        }
        
        /// <remarks/>
        public void Date_PlanAsync(string val, string val1, object userState) {
            if ((this.Date_PlanOperationCompleted == null)) {
                this.Date_PlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDate_PlanOperationCompleted);
            }
            this.InvokeAsync("Date_Plan", new object[] {
                        val,
                        val1}, this.Date_PlanOperationCompleted, userState);
        }
        
        private void OnDate_PlanOperationCompleted(object arg) {
            if ((this.Date_PlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Date_PlanCompleted(this, new Date_PlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Date_Repeated", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Date_Repeated(string val) {
            object[] results = this.Invoke("Date_Repeated", new object[] {
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Date_RepeatedAsync(string val) {
            this.Date_RepeatedAsync(val, null);
        }
        
        /// <remarks/>
        public void Date_RepeatedAsync(string val, object userState) {
            if ((this.Date_RepeatedOperationCompleted == null)) {
                this.Date_RepeatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDate_RepeatedOperationCompleted);
            }
            this.InvokeAsync("Date_Repeated", new object[] {
                        val}, this.Date_RepeatedOperationCompleted, userState);
        }
        
        private void OnDate_RepeatedOperationCompleted(object arg) {
            if ((this.Date_RepeatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Date_RepeatedCompleted(this, new Date_RepeatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DateRepeated", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DateRepeated() {
            object[] results = this.Invoke("DateRepeated", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DateRepeatedAsync() {
            this.DateRepeatedAsync(null);
        }
        
        /// <remarks/>
        public void DateRepeatedAsync(object userState) {
            if ((this.DateRepeatedOperationCompleted == null)) {
                this.DateRepeatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDateRepeatedOperationCompleted);
            }
            this.InvokeAsync("DateRepeated", new object[0], this.DateRepeatedOperationCompleted, userState);
        }
        
        private void OnDateRepeatedOperationCompleted(object arg) {
            if ((this.DateRepeatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DateRepeatedCompleted(this, new DateRepeatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Date_UnPlan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Date_UnPlan(string val) {
            object[] results = this.Invoke("Date_UnPlan", new object[] {
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Date_UnPlanAsync(string val) {
            this.Date_UnPlanAsync(val, null);
        }
        
        /// <remarks/>
        public void Date_UnPlanAsync(string val, object userState) {
            if ((this.Date_UnPlanOperationCompleted == null)) {
                this.Date_UnPlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDate_UnPlanOperationCompleted);
            }
            this.InvokeAsync("Date_UnPlan", new object[] {
                        val}, this.Date_UnPlanOperationCompleted, userState);
        }
        
        private void OnDate_UnPlanOperationCompleted(object arg) {
            if ((this.Date_UnPlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Date_UnPlanCompleted(this, new Date_UnPlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DateSurprise", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DateSurprise() {
            object[] results = this.Invoke("DateSurprise", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DateSurpriseAsync() {
            this.DateSurpriseAsync(null);
        }
        
        /// <remarks/>
        public void DateSurpriseAsync(object userState) {
            if ((this.DateSurpriseOperationCompleted == null)) {
                this.DateSurpriseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDateSurpriseOperationCompleted);
            }
            this.InvokeAsync("DateSurprise", new object[0], this.DateSurpriseOperationCompleted, userState);
        }
        
        private void OnDateSurpriseOperationCompleted(object arg) {
            if ((this.DateSurpriseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DateSurpriseCompleted(this, new DateSurpriseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Exists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Exists(string where) {
            object[] results = this.Invoke("Exists", new object[] {
                        where});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExistsAsync(string where) {
            this.ExistsAsync(where, null);
        }
        
        /// <remarks/>
        public void ExistsAsync(string where, object userState) {
            if ((this.ExistsOperationCompleted == null)) {
                this.ExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExistsOperationCompleted);
            }
            this.InvokeAsync("Exists", new object[] {
                        where}, this.ExistsOperationCompleted, userState);
        }
        
        private void OnExistsOperationCompleted(object arg) {
            if ((this.ExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExistsCompleted(this, new ExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Date_Surprise", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Date_Surprise(string val) {
            object[] results = this.Invoke("Date_Surprise", new object[] {
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Date_SurpriseAsync(string val) {
            this.Date_SurpriseAsync(val, null);
        }
        
        /// <remarks/>
        public void Date_SurpriseAsync(string val, object userState) {
            if ((this.Date_SurpriseOperationCompleted == null)) {
                this.Date_SurpriseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDate_SurpriseOperationCompleted);
            }
            this.InvokeAsync("Date_Surprise", new object[] {
                        val}, this.Date_SurpriseOperationCompleted, userState);
        }
        
        private void OnDate_SurpriseOperationCompleted(object arg) {
            if ((this.Date_SurpriseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Date_SurpriseCompleted(this, new Date_SurpriseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Validation_Duty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Validation_Duty(string where) {
            object[] results = this.Invoke("Validation_Duty", new object[] {
                        where});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Validation_DutyAsync(string where) {
            this.Validation_DutyAsync(where, null);
        }
        
        /// <remarks/>
        public void Validation_DutyAsync(string where, object userState) {
            if ((this.Validation_DutyOperationCompleted == null)) {
                this.Validation_DutyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidation_DutyOperationCompleted);
            }
            this.InvokeAsync("Validation_Duty", new object[] {
                        where}, this.Validation_DutyOperationCompleted, userState);
        }
        
        private void OnValidation_DutyOperationCompleted(object arg) {
            if ((this.Validation_DutyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Validation_DutyCompleted(this, new Validation_DutyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Commision", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Commision(string where) {
            object[] results = this.Invoke("Commision", new object[] {
                        where});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CommisionAsync(string where) {
            this.CommisionAsync(where, null);
        }
        
        /// <remarks/>
        public void CommisionAsync(string where, object userState) {
            if ((this.CommisionOperationCompleted == null)) {
                this.CommisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommisionOperationCompleted);
            }
            this.InvokeAsync("Commision", new object[] {
                        where}, this.CommisionOperationCompleted, userState);
        }
        
        private void OnCommisionOperationCompleted(object arg) {
            if ((this.CommisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CommisionCompleted(this, new CommisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Insert() {
            object[] results = this.Invoke("Insert", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void InsertAsync() {
            this.InsertAsync(null);
        }
        
        /// <remarks/>
        public void InsertAsync(object userState) {
            if ((this.InsertOperationCompleted == null)) {
                this.InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertOperationCompleted);
            }
            this.InvokeAsync("Insert", new object[0], this.InsertOperationCompleted, userState);
        }
        
        private void OnInsertOperationCompleted(object arg) {
            if ((this.InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCompleted(this, new InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WantRice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WantRice() {
            object[] results = this.Invoke("WantRice", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WantRiceAsync() {
            this.WantRiceAsync(null);
        }
        
        /// <remarks/>
        public void WantRiceAsync(object userState) {
            if ((this.WantRiceOperationCompleted == null)) {
                this.WantRiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWantRiceOperationCompleted);
            }
            this.InvokeAsync("WantRice", new object[0], this.WantRiceOperationCompleted, userState);
        }
        
        private void OnWantRiceOperationCompleted(object arg) {
            if ((this.WantRiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WantRiceCompleted(this, new WantRiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Date_Validation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Date_Validation(string val) {
            object[] results = this.Invoke("Date_Validation", new object[] {
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Date_ValidationAsync(string val) {
            this.Date_ValidationAsync(val, null);
        }
        
        /// <remarks/>
        public void Date_ValidationAsync(string val, object userState) {
            if ((this.Date_ValidationOperationCompleted == null)) {
                this.Date_ValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDate_ValidationOperationCompleted);
            }
            this.InvokeAsync("Date_Validation", new object[] {
                        val}, this.Date_ValidationOperationCompleted, userState);
        }
        
        private void OnDate_ValidationOperationCompleted(object arg) {
            if ((this.Date_ValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Date_ValidationCompleted(this, new Date_ValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Request", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Request() {
            object[] results = this.Invoke("Request", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RequestAsync() {
            this.RequestAsync(null);
        }
        
        /// <remarks/>
        public void RequestAsync(object userState) {
            if ((this.RequestOperationCompleted == null)) {
                this.RequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestOperationCompleted);
            }
            this.InvokeAsync("Request", new object[0], this.RequestOperationCompleted, userState);
        }
        
        private void OnRequestOperationCompleted(object arg) {
            if ((this.RequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestCompleted(this, new RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DateRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DateRequest() {
            object[] results = this.Invoke("DateRequest", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DateRequestAsync() {
            this.DateRequestAsync(null);
        }
        
        /// <remarks/>
        public void DateRequestAsync(object userState) {
            if ((this.DateRequestOperationCompleted == null)) {
                this.DateRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDateRequestOperationCompleted);
            }
            this.InvokeAsync("DateRequest", new object[0], this.DateRequestOperationCompleted, userState);
        }
        
        private void OnDateRequestOperationCompleted(object arg) {
            if ((this.DateRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DateRequestCompleted(this, new DateRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable wh(string where) {
            object[] results = this.Invoke("wh", new object[] {
                        where});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void whAsync(string where) {
            this.whAsync(where, null);
        }
        
        /// <remarks/>
        public void whAsync(string where, object userState) {
            if ((this.whOperationCompleted == null)) {
                this.whOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwhOperationCompleted);
            }
            this.InvokeAsync("wh", new object[] {
                        where}, this.whOperationCompleted, userState);
        }
        
        private void OnwhOperationCompleted(object arg) {
            if ((this.whCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.whCompleted(this, new whCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Employees", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Employees(string where) {
            object[] results = this.Invoke("Employees", new object[] {
                        where});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void EmployeesAsync(string where) {
            this.EmployeesAsync(where, null);
        }
        
        /// <remarks/>
        public void EmployeesAsync(string where, object userState) {
            if ((this.EmployeesOperationCompleted == null)) {
                this.EmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeesOperationCompleted);
            }
            this.InvokeAsync("Employees", new object[] {
                        where}, this.EmployeesOperationCompleted, userState);
        }
        
        private void OnEmployeesOperationCompleted(object arg) {
            if ((this.EmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeesCompleted(this, new EmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GovernmentMan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GovernmentMan() {
            object[] results = this.Invoke("GovernmentMan", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GovernmentManAsync() {
            this.GovernmentManAsync(null);
        }
        
        /// <remarks/>
        public void GovernmentManAsync(object userState) {
            if ((this.GovernmentManOperationCompleted == null)) {
                this.GovernmentManOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGovernmentManOperationCompleted);
            }
            this.InvokeAsync("GovernmentMan", new object[0], this.GovernmentManOperationCompleted, userState);
        }
        
        private void OnGovernmentManOperationCompleted(object arg) {
            if ((this.GovernmentManCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GovernmentManCompleted(this, new GovernmentManCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ApproveAttestationRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ApproveAttestationUnPlanCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ApproveAttestationReCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ApproveAttestationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ApproveDataDeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ApproveDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GovernmentCompletedEventHandler(object sender, GovernmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GovernmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GovernmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Fill_CommissionCompletedEventHandler(object sender, Fill_CommissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fill_CommissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fill_CommissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Commission_AppointedCompletedEventHandler(object sender, Commission_AppointedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Commission_AppointedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Commission_AppointedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void StatementReverseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void StatementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ProFileCompletedEventHandler(object sender, ProFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] array1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] array2 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] array3 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AuthentificationCompletedEventHandler(object sender, AuthentificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthentificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthentificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int who {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Date_PlanCompletedEventHandler(object sender, Date_PlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Date_PlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Date_PlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Date_RepeatedCompletedEventHandler(object sender, Date_RepeatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Date_RepeatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Date_RepeatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DateRepeatedCompletedEventHandler(object sender, DateRepeatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DateRepeatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DateRepeatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Date_UnPlanCompletedEventHandler(object sender, Date_UnPlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Date_UnPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Date_UnPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DateSurpriseCompletedEventHandler(object sender, DateSurpriseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DateSurpriseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DateSurpriseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ExistsCompletedEventHandler(object sender, ExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Date_SurpriseCompletedEventHandler(object sender, Date_SurpriseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Date_SurpriseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Date_SurpriseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Validation_DutyCompletedEventHandler(object sender, Validation_DutyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Validation_DutyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Validation_DutyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CommisionCompletedEventHandler(object sender, CommisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CommisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CommisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InsertCompletedEventHandler(object sender, InsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void WantRiceCompletedEventHandler(object sender, WantRiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WantRiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WantRiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Date_ValidationCompletedEventHandler(object sender, Date_ValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Date_ValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Date_ValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RequestCompletedEventHandler(object sender, RequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DateRequestCompletedEventHandler(object sender, DateRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DateRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DateRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void whCompletedEventHandler(object sender, whCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class whCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal whCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void EmployeesCompletedEventHandler(object sender, EmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GovernmentManCompletedEventHandler(object sender, GovernmentManCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GovernmentManCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GovernmentManCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591